name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, '**' ]

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.5'

    - name: Run Go Linting
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        skip-cache: true
        only-new-issues: false
        args: --out-format=colored-line-number --timeout=5m --config=.golangci.yml
    
    - name: Generate porcelain check
      run: |
        make generate
        FILES_MODIFIED="$(git status --porcelain)"
        if [[ -n "$FILES_MODIFIED" ]]; then
            echo "The following files were modified or added during the generate process:"
            echo "$FILES_MODIFIED"
            exit 1
        fi    
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'

    - name: Run unit tests
      run: make test > test_output.txt

    - name: Generate test coverage report
      run: go tool cover -html=./cover.out -o ./cover.html

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./cover.html

    - name: Upload test_output report
      uses: actions/upload-artifact@v4
      with:
        name: test_output
        path: ./test_output.txt

  build:
    runs-on: ubuntu-latest
    needs:
      - test
      - lint

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'

    - name: Build application
      run: |
        echo "Building application to verify compilation..."
        go build -o bin/swolegen-api ./cmd/swolegen-api
        echo "✅ Application builds successfully"
